# Generated by Django 3.2.4 on 2021-08-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100, unique=True)),
                ('Endereco', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=25, unique=True)),
                ('CNPJ', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
    ]
